/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminAuthenticatedRouteImport } from './routes/admin/_authenticated'
import { Route as AdminAuthenticatedIndexRouteImport } from './routes/admin/_authenticated/index'
import { Route as AdminAuthenticatedSettingsRouteImport } from './routes/admin/_authenticated/settings'
import { Route as AdminAuthenticatedMessagesRouteImport } from './routes/admin/_authenticated/messages'
import { Route as AdminAuthenticatedFaqRouteImport } from './routes/admin/_authenticated/faq'
import { Route as AdminAuthenticatedTestimonialsIndexRouteImport } from './routes/admin/_authenticated/testimonials/index'
import { Route as AdminAuthenticatedReservationsIndexRouteImport } from './routes/admin/_authenticated/reservations/index'
import { Route as AdminAuthenticatedOffersIndexRouteImport } from './routes/admin/_authenticated/offers/index'
import { Route as AdminAuthenticatedMenuIndexRouteImport } from './routes/admin/_authenticated/menu/index'
import { Route as AdminAuthenticatedGalleryIndexRouteImport } from './routes/admin/_authenticated/gallery/index'
import { Route as AdminAuthenticatedChefsIndexRouteImport } from './routes/admin/_authenticated/chefs/index'
import { Route as AdminAuthenticatedTestimonialsNewRouteImport } from './routes/admin/_authenticated/testimonials/new'
import { Route as AdminAuthenticatedReservationsReservationIdRouteImport } from './routes/admin/_authenticated/reservations/$reservationId'
import { Route as AdminAuthenticatedOffersNewRouteImport } from './routes/admin/_authenticated/offers/new'
import { Route as AdminAuthenticatedMenuNewRouteImport } from './routes/admin/_authenticated/menu/new'
import { Route as AdminAuthenticatedGalleryNewRouteImport } from './routes/admin/_authenticated/gallery/new'
import { Route as AdminAuthenticatedContentHeroRouteImport } from './routes/admin/_authenticated/content/hero'
import { Route as AdminAuthenticatedContentAboutRouteImport } from './routes/admin/_authenticated/content/about'
import { Route as AdminAuthenticatedChefsNewRouteImport } from './routes/admin/_authenticated/chefs/new'
import { Route as AdminAuthenticatedTestimonialsTestimonialIdEditRouteImport } from './routes/admin/_authenticated/testimonials/$testimonialId/edit'
import { Route as AdminAuthenticatedOffersOfferIdEditRouteImport } from './routes/admin/_authenticated/offers/$offerId/edit'
import { Route as AdminAuthenticatedMenuMenuIdEditRouteImport } from './routes/admin/_authenticated/menu/$menuId/edit'
import { Route as AdminAuthenticatedGalleryImageIdEditRouteImport } from './routes/admin/_authenticated/gallery/$imageId/edit'
import { Route as AdminAuthenticatedChefsChefIdEditRouteImport } from './routes/admin/_authenticated/chefs/$chefId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthenticatedRoute = AdminAuthenticatedRouteImport.update({
  id: '/admin/_authenticated',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthenticatedIndexRoute = AdminAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminAuthenticatedSettingsRoute =
  AdminAuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedMessagesRoute =
  AdminAuthenticatedMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedFaqRoute = AdminAuthenticatedFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminAuthenticatedTestimonialsIndexRoute =
  AdminAuthenticatedTestimonialsIndexRouteImport.update({
    id: '/testimonials/',
    path: '/testimonials/',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedReservationsIndexRoute =
  AdminAuthenticatedReservationsIndexRouteImport.update({
    id: '/reservations/',
    path: '/reservations/',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedOffersIndexRoute =
  AdminAuthenticatedOffersIndexRouteImport.update({
    id: '/offers/',
    path: '/offers/',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedMenuIndexRoute =
  AdminAuthenticatedMenuIndexRouteImport.update({
    id: '/menu/',
    path: '/menu/',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedGalleryIndexRoute =
  AdminAuthenticatedGalleryIndexRouteImport.update({
    id: '/gallery/',
    path: '/gallery/',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedChefsIndexRoute =
  AdminAuthenticatedChefsIndexRouteImport.update({
    id: '/chefs/',
    path: '/chefs/',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedTestimonialsNewRoute =
  AdminAuthenticatedTestimonialsNewRouteImport.update({
    id: '/testimonials/new',
    path: '/testimonials/new',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedReservationsReservationIdRoute =
  AdminAuthenticatedReservationsReservationIdRouteImport.update({
    id: '/reservations/$reservationId',
    path: '/reservations/$reservationId',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedOffersNewRoute =
  AdminAuthenticatedOffersNewRouteImport.update({
    id: '/offers/new',
    path: '/offers/new',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedMenuNewRoute =
  AdminAuthenticatedMenuNewRouteImport.update({
    id: '/menu/new',
    path: '/menu/new',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedGalleryNewRoute =
  AdminAuthenticatedGalleryNewRouteImport.update({
    id: '/gallery/new',
    path: '/gallery/new',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedContentHeroRoute =
  AdminAuthenticatedContentHeroRouteImport.update({
    id: '/content/hero',
    path: '/content/hero',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedContentAboutRoute =
  AdminAuthenticatedContentAboutRouteImport.update({
    id: '/content/about',
    path: '/content/about',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedChefsNewRoute =
  AdminAuthenticatedChefsNewRouteImport.update({
    id: '/chefs/new',
    path: '/chefs/new',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedTestimonialsTestimonialIdEditRoute =
  AdminAuthenticatedTestimonialsTestimonialIdEditRouteImport.update({
    id: '/testimonials/$testimonialId/edit',
    path: '/testimonials/$testimonialId/edit',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedOffersOfferIdEditRoute =
  AdminAuthenticatedOffersOfferIdEditRouteImport.update({
    id: '/offers/$offerId/edit',
    path: '/offers/$offerId/edit',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedMenuMenuIdEditRoute =
  AdminAuthenticatedMenuMenuIdEditRouteImport.update({
    id: '/menu/$menuId/edit',
    path: '/menu/$menuId/edit',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedGalleryImageIdEditRoute =
  AdminAuthenticatedGalleryImageIdEditRouteImport.update({
    id: '/gallery/$imageId/edit',
    path: '/gallery/$imageId/edit',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedChefsChefIdEditRoute =
  AdminAuthenticatedChefsChefIdEditRouteImport.update({
    id: '/chefs/$chefId/edit',
    path: '/chefs/$chefId/edit',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminAuthenticatedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/faq': typeof AdminAuthenticatedFaqRoute
  '/admin/messages': typeof AdminAuthenticatedMessagesRoute
  '/admin/settings': typeof AdminAuthenticatedSettingsRoute
  '/admin/': typeof AdminAuthenticatedIndexRoute
  '/admin/chefs/new': typeof AdminAuthenticatedChefsNewRoute
  '/admin/content/about': typeof AdminAuthenticatedContentAboutRoute
  '/admin/content/hero': typeof AdminAuthenticatedContentHeroRoute
  '/admin/gallery/new': typeof AdminAuthenticatedGalleryNewRoute
  '/admin/menu/new': typeof AdminAuthenticatedMenuNewRoute
  '/admin/offers/new': typeof AdminAuthenticatedOffersNewRoute
  '/admin/reservations/$reservationId': typeof AdminAuthenticatedReservationsReservationIdRoute
  '/admin/testimonials/new': typeof AdminAuthenticatedTestimonialsNewRoute
  '/admin/chefs/': typeof AdminAuthenticatedChefsIndexRoute
  '/admin/gallery/': typeof AdminAuthenticatedGalleryIndexRoute
  '/admin/menu/': typeof AdminAuthenticatedMenuIndexRoute
  '/admin/offers/': typeof AdminAuthenticatedOffersIndexRoute
  '/admin/reservations/': typeof AdminAuthenticatedReservationsIndexRoute
  '/admin/testimonials/': typeof AdminAuthenticatedTestimonialsIndexRoute
  '/admin/chefs/$chefId/edit': typeof AdminAuthenticatedChefsChefIdEditRoute
  '/admin/gallery/$imageId/edit': typeof AdminAuthenticatedGalleryImageIdEditRoute
  '/admin/menu/$menuId/edit': typeof AdminAuthenticatedMenuMenuIdEditRoute
  '/admin/offers/$offerId/edit': typeof AdminAuthenticatedOffersOfferIdEditRoute
  '/admin/testimonials/$testimonialId/edit': typeof AdminAuthenticatedTestimonialsTestimonialIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/faq': typeof AdminAuthenticatedFaqRoute
  '/admin/messages': typeof AdminAuthenticatedMessagesRoute
  '/admin/settings': typeof AdminAuthenticatedSettingsRoute
  '/admin': typeof AdminAuthenticatedIndexRoute
  '/admin/chefs/new': typeof AdminAuthenticatedChefsNewRoute
  '/admin/content/about': typeof AdminAuthenticatedContentAboutRoute
  '/admin/content/hero': typeof AdminAuthenticatedContentHeroRoute
  '/admin/gallery/new': typeof AdminAuthenticatedGalleryNewRoute
  '/admin/menu/new': typeof AdminAuthenticatedMenuNewRoute
  '/admin/offers/new': typeof AdminAuthenticatedOffersNewRoute
  '/admin/reservations/$reservationId': typeof AdminAuthenticatedReservationsReservationIdRoute
  '/admin/testimonials/new': typeof AdminAuthenticatedTestimonialsNewRoute
  '/admin/chefs': typeof AdminAuthenticatedChefsIndexRoute
  '/admin/gallery': typeof AdminAuthenticatedGalleryIndexRoute
  '/admin/menu': typeof AdminAuthenticatedMenuIndexRoute
  '/admin/offers': typeof AdminAuthenticatedOffersIndexRoute
  '/admin/reservations': typeof AdminAuthenticatedReservationsIndexRoute
  '/admin/testimonials': typeof AdminAuthenticatedTestimonialsIndexRoute
  '/admin/chefs/$chefId/edit': typeof AdminAuthenticatedChefsChefIdEditRoute
  '/admin/gallery/$imageId/edit': typeof AdminAuthenticatedGalleryImageIdEditRoute
  '/admin/menu/$menuId/edit': typeof AdminAuthenticatedMenuMenuIdEditRoute
  '/admin/offers/$offerId/edit': typeof AdminAuthenticatedOffersOfferIdEditRoute
  '/admin/testimonials/$testimonialId/edit': typeof AdminAuthenticatedTestimonialsTestimonialIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_authenticated': typeof AdminAuthenticatedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/_authenticated/faq': typeof AdminAuthenticatedFaqRoute
  '/admin/_authenticated/messages': typeof AdminAuthenticatedMessagesRoute
  '/admin/_authenticated/settings': typeof AdminAuthenticatedSettingsRoute
  '/admin/_authenticated/': typeof AdminAuthenticatedIndexRoute
  '/admin/_authenticated/chefs/new': typeof AdminAuthenticatedChefsNewRoute
  '/admin/_authenticated/content/about': typeof AdminAuthenticatedContentAboutRoute
  '/admin/_authenticated/content/hero': typeof AdminAuthenticatedContentHeroRoute
  '/admin/_authenticated/gallery/new': typeof AdminAuthenticatedGalleryNewRoute
  '/admin/_authenticated/menu/new': typeof AdminAuthenticatedMenuNewRoute
  '/admin/_authenticated/offers/new': typeof AdminAuthenticatedOffersNewRoute
  '/admin/_authenticated/reservations/$reservationId': typeof AdminAuthenticatedReservationsReservationIdRoute
  '/admin/_authenticated/testimonials/new': typeof AdminAuthenticatedTestimonialsNewRoute
  '/admin/_authenticated/chefs/': typeof AdminAuthenticatedChefsIndexRoute
  '/admin/_authenticated/gallery/': typeof AdminAuthenticatedGalleryIndexRoute
  '/admin/_authenticated/menu/': typeof AdminAuthenticatedMenuIndexRoute
  '/admin/_authenticated/offers/': typeof AdminAuthenticatedOffersIndexRoute
  '/admin/_authenticated/reservations/': typeof AdminAuthenticatedReservationsIndexRoute
  '/admin/_authenticated/testimonials/': typeof AdminAuthenticatedTestimonialsIndexRoute
  '/admin/_authenticated/chefs/$chefId/edit': typeof AdminAuthenticatedChefsChefIdEditRoute
  '/admin/_authenticated/gallery/$imageId/edit': typeof AdminAuthenticatedGalleryImageIdEditRoute
  '/admin/_authenticated/menu/$menuId/edit': typeof AdminAuthenticatedMenuMenuIdEditRoute
  '/admin/_authenticated/offers/$offerId/edit': typeof AdminAuthenticatedOffersOfferIdEditRoute
  '/admin/_authenticated/testimonials/$testimonialId/edit': typeof AdminAuthenticatedTestimonialsTestimonialIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/admin/faq'
    | '/admin/messages'
    | '/admin/settings'
    | '/admin/'
    | '/admin/chefs/new'
    | '/admin/content/about'
    | '/admin/content/hero'
    | '/admin/gallery/new'
    | '/admin/menu/new'
    | '/admin/offers/new'
    | '/admin/reservations/$reservationId'
    | '/admin/testimonials/new'
    | '/admin/chefs/'
    | '/admin/gallery/'
    | '/admin/menu/'
    | '/admin/offers/'
    | '/admin/reservations/'
    | '/admin/testimonials/'
    | '/admin/chefs/$chefId/edit'
    | '/admin/gallery/$imageId/edit'
    | '/admin/menu/$menuId/edit'
    | '/admin/offers/$offerId/edit'
    | '/admin/testimonials/$testimonialId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/admin/faq'
    | '/admin/messages'
    | '/admin/settings'
    | '/admin'
    | '/admin/chefs/new'
    | '/admin/content/about'
    | '/admin/content/hero'
    | '/admin/gallery/new'
    | '/admin/menu/new'
    | '/admin/offers/new'
    | '/admin/reservations/$reservationId'
    | '/admin/testimonials/new'
    | '/admin/chefs'
    | '/admin/gallery'
    | '/admin/menu'
    | '/admin/offers'
    | '/admin/reservations'
    | '/admin/testimonials'
    | '/admin/chefs/$chefId/edit'
    | '/admin/gallery/$imageId/edit'
    | '/admin/menu/$menuId/edit'
    | '/admin/offers/$offerId/edit'
    | '/admin/testimonials/$testimonialId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin/_authenticated'
    | '/admin/login'
    | '/admin/_authenticated/faq'
    | '/admin/_authenticated/messages'
    | '/admin/_authenticated/settings'
    | '/admin/_authenticated/'
    | '/admin/_authenticated/chefs/new'
    | '/admin/_authenticated/content/about'
    | '/admin/_authenticated/content/hero'
    | '/admin/_authenticated/gallery/new'
    | '/admin/_authenticated/menu/new'
    | '/admin/_authenticated/offers/new'
    | '/admin/_authenticated/reservations/$reservationId'
    | '/admin/_authenticated/testimonials/new'
    | '/admin/_authenticated/chefs/'
    | '/admin/_authenticated/gallery/'
    | '/admin/_authenticated/menu/'
    | '/admin/_authenticated/offers/'
    | '/admin/_authenticated/reservations/'
    | '/admin/_authenticated/testimonials/'
    | '/admin/_authenticated/chefs/$chefId/edit'
    | '/admin/_authenticated/gallery/$imageId/edit'
    | '/admin/_authenticated/menu/$menuId/edit'
    | '/admin/_authenticated/offers/$offerId/edit'
    | '/admin/_authenticated/testimonials/$testimonialId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAuthenticatedRoute: typeof AdminAuthenticatedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authenticated': {
      id: '/admin/_authenticated'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authenticated/': {
      id: '/admin/_authenticated/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthenticatedIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/settings': {
      id: '/admin/_authenticated/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAuthenticatedSettingsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/messages': {
      id: '/admin/_authenticated/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminAuthenticatedMessagesRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/faq': {
      id: '/admin/_authenticated/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AdminAuthenticatedFaqRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/testimonials/': {
      id: '/admin/_authenticated/testimonials/'
      path: '/testimonials'
      fullPath: '/admin/testimonials/'
      preLoaderRoute: typeof AdminAuthenticatedTestimonialsIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/reservations/': {
      id: '/admin/_authenticated/reservations/'
      path: '/reservations'
      fullPath: '/admin/reservations/'
      preLoaderRoute: typeof AdminAuthenticatedReservationsIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/offers/': {
      id: '/admin/_authenticated/offers/'
      path: '/offers'
      fullPath: '/admin/offers/'
      preLoaderRoute: typeof AdminAuthenticatedOffersIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/menu/': {
      id: '/admin/_authenticated/menu/'
      path: '/menu'
      fullPath: '/admin/menu/'
      preLoaderRoute: typeof AdminAuthenticatedMenuIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/gallery/': {
      id: '/admin/_authenticated/gallery/'
      path: '/gallery'
      fullPath: '/admin/gallery/'
      preLoaderRoute: typeof AdminAuthenticatedGalleryIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/chefs/': {
      id: '/admin/_authenticated/chefs/'
      path: '/chefs'
      fullPath: '/admin/chefs/'
      preLoaderRoute: typeof AdminAuthenticatedChefsIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/testimonials/new': {
      id: '/admin/_authenticated/testimonials/new'
      path: '/testimonials/new'
      fullPath: '/admin/testimonials/new'
      preLoaderRoute: typeof AdminAuthenticatedTestimonialsNewRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/reservations/$reservationId': {
      id: '/admin/_authenticated/reservations/$reservationId'
      path: '/reservations/$reservationId'
      fullPath: '/admin/reservations/$reservationId'
      preLoaderRoute: typeof AdminAuthenticatedReservationsReservationIdRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/offers/new': {
      id: '/admin/_authenticated/offers/new'
      path: '/offers/new'
      fullPath: '/admin/offers/new'
      preLoaderRoute: typeof AdminAuthenticatedOffersNewRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/menu/new': {
      id: '/admin/_authenticated/menu/new'
      path: '/menu/new'
      fullPath: '/admin/menu/new'
      preLoaderRoute: typeof AdminAuthenticatedMenuNewRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/gallery/new': {
      id: '/admin/_authenticated/gallery/new'
      path: '/gallery/new'
      fullPath: '/admin/gallery/new'
      preLoaderRoute: typeof AdminAuthenticatedGalleryNewRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/content/hero': {
      id: '/admin/_authenticated/content/hero'
      path: '/content/hero'
      fullPath: '/admin/content/hero'
      preLoaderRoute: typeof AdminAuthenticatedContentHeroRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/content/about': {
      id: '/admin/_authenticated/content/about'
      path: '/content/about'
      fullPath: '/admin/content/about'
      preLoaderRoute: typeof AdminAuthenticatedContentAboutRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/chefs/new': {
      id: '/admin/_authenticated/chefs/new'
      path: '/chefs/new'
      fullPath: '/admin/chefs/new'
      preLoaderRoute: typeof AdminAuthenticatedChefsNewRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/testimonials/$testimonialId/edit': {
      id: '/admin/_authenticated/testimonials/$testimonialId/edit'
      path: '/testimonials/$testimonialId/edit'
      fullPath: '/admin/testimonials/$testimonialId/edit'
      preLoaderRoute: typeof AdminAuthenticatedTestimonialsTestimonialIdEditRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/offers/$offerId/edit': {
      id: '/admin/_authenticated/offers/$offerId/edit'
      path: '/offers/$offerId/edit'
      fullPath: '/admin/offers/$offerId/edit'
      preLoaderRoute: typeof AdminAuthenticatedOffersOfferIdEditRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/menu/$menuId/edit': {
      id: '/admin/_authenticated/menu/$menuId/edit'
      path: '/menu/$menuId/edit'
      fullPath: '/admin/menu/$menuId/edit'
      preLoaderRoute: typeof AdminAuthenticatedMenuMenuIdEditRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/gallery/$imageId/edit': {
      id: '/admin/_authenticated/gallery/$imageId/edit'
      path: '/gallery/$imageId/edit'
      fullPath: '/admin/gallery/$imageId/edit'
      preLoaderRoute: typeof AdminAuthenticatedGalleryImageIdEditRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/chefs/$chefId/edit': {
      id: '/admin/_authenticated/chefs/$chefId/edit'
      path: '/chefs/$chefId/edit'
      fullPath: '/admin/chefs/$chefId/edit'
      preLoaderRoute: typeof AdminAuthenticatedChefsChefIdEditRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
  }
}

interface AdminAuthenticatedRouteChildren {
  AdminAuthenticatedFaqRoute: typeof AdminAuthenticatedFaqRoute
  AdminAuthenticatedMessagesRoute: typeof AdminAuthenticatedMessagesRoute
  AdminAuthenticatedSettingsRoute: typeof AdminAuthenticatedSettingsRoute
  AdminAuthenticatedIndexRoute: typeof AdminAuthenticatedIndexRoute
  AdminAuthenticatedChefsNewRoute: typeof AdminAuthenticatedChefsNewRoute
  AdminAuthenticatedContentAboutRoute: typeof AdminAuthenticatedContentAboutRoute
  AdminAuthenticatedContentHeroRoute: typeof AdminAuthenticatedContentHeroRoute
  AdminAuthenticatedGalleryNewRoute: typeof AdminAuthenticatedGalleryNewRoute
  AdminAuthenticatedMenuNewRoute: typeof AdminAuthenticatedMenuNewRoute
  AdminAuthenticatedOffersNewRoute: typeof AdminAuthenticatedOffersNewRoute
  AdminAuthenticatedReservationsReservationIdRoute: typeof AdminAuthenticatedReservationsReservationIdRoute
  AdminAuthenticatedTestimonialsNewRoute: typeof AdminAuthenticatedTestimonialsNewRoute
  AdminAuthenticatedChefsIndexRoute: typeof AdminAuthenticatedChefsIndexRoute
  AdminAuthenticatedGalleryIndexRoute: typeof AdminAuthenticatedGalleryIndexRoute
  AdminAuthenticatedMenuIndexRoute: typeof AdminAuthenticatedMenuIndexRoute
  AdminAuthenticatedOffersIndexRoute: typeof AdminAuthenticatedOffersIndexRoute
  AdminAuthenticatedReservationsIndexRoute: typeof AdminAuthenticatedReservationsIndexRoute
  AdminAuthenticatedTestimonialsIndexRoute: typeof AdminAuthenticatedTestimonialsIndexRoute
  AdminAuthenticatedChefsChefIdEditRoute: typeof AdminAuthenticatedChefsChefIdEditRoute
  AdminAuthenticatedGalleryImageIdEditRoute: typeof AdminAuthenticatedGalleryImageIdEditRoute
  AdminAuthenticatedMenuMenuIdEditRoute: typeof AdminAuthenticatedMenuMenuIdEditRoute
  AdminAuthenticatedOffersOfferIdEditRoute: typeof AdminAuthenticatedOffersOfferIdEditRoute
  AdminAuthenticatedTestimonialsTestimonialIdEditRoute: typeof AdminAuthenticatedTestimonialsTestimonialIdEditRoute
}

const AdminAuthenticatedRouteChildren: AdminAuthenticatedRouteChildren = {
  AdminAuthenticatedFaqRoute: AdminAuthenticatedFaqRoute,
  AdminAuthenticatedMessagesRoute: AdminAuthenticatedMessagesRoute,
  AdminAuthenticatedSettingsRoute: AdminAuthenticatedSettingsRoute,
  AdminAuthenticatedIndexRoute: AdminAuthenticatedIndexRoute,
  AdminAuthenticatedChefsNewRoute: AdminAuthenticatedChefsNewRoute,
  AdminAuthenticatedContentAboutRoute: AdminAuthenticatedContentAboutRoute,
  AdminAuthenticatedContentHeroRoute: AdminAuthenticatedContentHeroRoute,
  AdminAuthenticatedGalleryNewRoute: AdminAuthenticatedGalleryNewRoute,
  AdminAuthenticatedMenuNewRoute: AdminAuthenticatedMenuNewRoute,
  AdminAuthenticatedOffersNewRoute: AdminAuthenticatedOffersNewRoute,
  AdminAuthenticatedReservationsReservationIdRoute:
    AdminAuthenticatedReservationsReservationIdRoute,
  AdminAuthenticatedTestimonialsNewRoute:
    AdminAuthenticatedTestimonialsNewRoute,
  AdminAuthenticatedChefsIndexRoute: AdminAuthenticatedChefsIndexRoute,
  AdminAuthenticatedGalleryIndexRoute: AdminAuthenticatedGalleryIndexRoute,
  AdminAuthenticatedMenuIndexRoute: AdminAuthenticatedMenuIndexRoute,
  AdminAuthenticatedOffersIndexRoute: AdminAuthenticatedOffersIndexRoute,
  AdminAuthenticatedReservationsIndexRoute:
    AdminAuthenticatedReservationsIndexRoute,
  AdminAuthenticatedTestimonialsIndexRoute:
    AdminAuthenticatedTestimonialsIndexRoute,
  AdminAuthenticatedChefsChefIdEditRoute:
    AdminAuthenticatedChefsChefIdEditRoute,
  AdminAuthenticatedGalleryImageIdEditRoute:
    AdminAuthenticatedGalleryImageIdEditRoute,
  AdminAuthenticatedMenuMenuIdEditRoute: AdminAuthenticatedMenuMenuIdEditRoute,
  AdminAuthenticatedOffersOfferIdEditRoute:
    AdminAuthenticatedOffersOfferIdEditRoute,
  AdminAuthenticatedTestimonialsTestimonialIdEditRoute:
    AdminAuthenticatedTestimonialsTestimonialIdEditRoute,
}

const AdminAuthenticatedRouteWithChildren =
  AdminAuthenticatedRoute._addFileChildren(AdminAuthenticatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAuthenticatedRoute: AdminAuthenticatedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
